# Generated by Django 5.1.7 on 2025-03-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digestapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='book_id',
            new_name='book',
        ),
    ]
